(function(){
var CITIES=[{"name": "Damascus", "url": "maryland/montgomery-county/damascus/", "county": "Montgomery County"}, {"name": "Gaithersburg", "url": "maryland/montgomery-county/gaithersburg/", "county": "Montgomery County"}, {"name": "Germantown", "url": "maryland/montgomery-county/germantown/", "county": "Montgomery County"}, {"name": "Olney", "url": "maryland/montgomery-county/olney/", "county": "Montgomery County"}, {"name": "Rockville", "url": "maryland/montgomery-county/rockville/", "county": "Montgomery County"}, {"name": "Silver Spring", "url": "maryland/montgomery-county/silver-spring/", "county": "Montgomery County"}, {"name": "Wheaton", "url": "maryland/montgomery-county/wheaton/", "county": "Montgomery County"}, {"name": "Baltimore", "url": "maryland/baltimore/baltimore/", "county": "Baltimore City & County"}, {"name": "Catonsville", "url": "maryland/baltimore/catonsville/", "county": "Baltimore City & County"}, {"name": "Cockeysville", "url": "maryland/baltimore/cockeysville/", "county": "Baltimore City & County"}, {"name": "Dundalk", "url": "maryland/baltimore/dundalk/", "county": "Baltimore City & County"}, {"name": "Essex", "url": "maryland/baltimore/essex/", "county": "Baltimore City & County"}, {"name": "Halethorpe", "url": "maryland/baltimore/halethorpe/", "county": "Baltimore City & County"}, {"name": "Nottingham", "url": "maryland/baltimore/nottingham/", "county": "Baltimore City & County"}, {"name": "Owings Mills", "url": "maryland/baltimore/owings-mills/", "county": "Baltimore City & County"}, {"name": "Parkville", "url": "maryland/baltimore/parkville/", "county": "Baltimore City & County"}, {"name": "Pikesville", "url": "maryland/baltimore/pikesville/", "county": "Baltimore City & County"}, {"name": "Timonium", "url": "maryland/baltimore/timonium/", "county": "Baltimore City & County"}, {"name": "Towson", "url": "maryland/baltimore/towson/", "county": "Baltimore City & County"}, {"name": "White Marsh", "url": "maryland/baltimore/white-marsh/", "county": "Baltimore City & County"}, {"name": "Woodlawn", "url": "maryland/baltimore/woodlawn/", "county": "Baltimore City & County"}];
var form=document.getElementById('cityFinder'),input=document.getElementById('cityInput'),msg=document.getElementById('finderMsg');
form.addEventListener('submit',function(e){
  e.preventDefault();
  var q=input.value.trim().toLowerCase();
  if(!q)return;
  var exact=CITIES.find(function(c){return c.name.toLowerCase()===q});
  var partial=exact||CITIES.find(function(c){return c.name.toLowerCase().indexOf(q)===0})||CITIES.find(function(c){return c.name.toLowerCase().indexOf(q)!==-1});
  if(partial){window.location.href=partial.url;}
  else{msg.textContent="We don't have "+input.value.trim()+" yet \u2014 browse Montgomery County or Baltimore below.";msg.style.color='var(--red)';}
});
})();